### ISSUE TITLE
addNewLink appears twice

### ISSUE THREAD

**Issue by kixe** [thetuningspoon/AdminPageFieldEditLinks#12]
If both, ProcessWire input setting: **'Allow new pages to be created from field?'** and the additional setting option assigned by the AdminPageFieldEditLinks module: **'Activate link to create new pages?'** are checked, the Link to add new pages appears twice.

![Bildschirmfoto 2021-06-03 um 07 17 28](https://user-images.githubusercontent.com/4683120/120591906-3a97ad00-c43d-11eb-85d7-b6495027d092.png)

To prevent this modify selector in js function **initEditLinks()**
https://github.com/thetuningspoon/AdminPageFieldEditLinks/blob/fdd7d0d7043858d0a9e754579b194479fecc72b4/AdminPageFieldEditLinks.js#L34

```
$wrapper.find('.InputfieldContent > .InputfieldPage-newPageLink').each(function () {

```

I vote for generally deactivate **'Allow creation of new pages from field?'** if **'Enable link to create new pages?'** is activated. It's a bit confusing and pretty useless. The following code would be one possibility of implementation:
https://github.com/thetuningspoon/AdminPageFieldEditLinks/blob/fdd7d0d7043858d0a9e754579b194479fecc72b4/AdminPageFieldEditLinks.module#L61

Prevent activation

```
if($that->newPageLink) {
	$event->return->addable->setAttribute('checked',false);
	$event->return->addable->setAttribute('disabled',true);
	$event->return->addable->notes = __('DISABLED: Not compatible with AdminPageFieldEditLinks');
}
```

Hide the field in edit screen

```
/**
 * Removes default create new link if add link is provided
 *
 */
$this->addHookBefore("InputfieldPage::renderAddable", function($event) {
	$that = $event->object;
	if($that->newPageLink) {
		$event->replace = true;
		$event->return = '';
	}
});

```

**Comment by thetuningspoon** [comment]
Thanks @kixe. I merged your pull request.
