### ISSUE TITLE
When page and field are included in modal link, field names with underscores don't work as expected

### ISSUE THREAD

**Issue by teppokoivula** [thetuningspoon/AdminPageFieldEditLinks#14]
Related to https://github.com/thetuningspoon/AdminPageFieldEditLinks/pull/13 (ping @kixe), it seems that currently field names with underscores (a pretty typical case) don't work: instead of "field_name", the value gets populated as "field".

Not tested, but this:

```
var fieldName = $pageField.parents('li.InputfieldPage').children('label').attr('for').split('_')[1];
```

Should probably be something like this instead:

```
var fieldName = $pageField.parents('li.InputfieldPage').children('label').attr('for').replace(/^Inputfield_/, '');
```

**Comment by kixe** [comment]
@teppokoivula 
Thanks for the hint. I hadn't considered the option for field names including underscores.
@thetuningspoon
This should be corrected in the recommended way.

**Comment by thetuningspoon** [comment]
Thanks @teppokoivula. I added your recommended fix. Let me know if there is any further issue.
