### ISSUE TITLE
Request: Possibility to add Processes via Api or Config Screen

### ISSUE THREAD

**Issue by gingebaker** [thetuningspoon/AdminPageFieldEditLinks#7]
I would like to also add the EditLinks on a special custom ProcessModule .

There is this private var wich I cannot change without modifying your module file.
https://github.com/thetuningspoon/AdminPageFieldEditLinks/blob/master/AdminPageFieldEditLinks.module#L10

It would be nice to have  the possibility to add a process.
something like:

``` php
public function addProcess($name) {
   $this->processes[] = $name;
}
```

or via config select field?

Could also do a PullRequest if you like?

**Comment by thetuningspoon** [comment]
I feel like there is probably a simpler way to do this that doesn't require listing out every single process module. If not, adding it to the module config would be ideal.

**Comment by gingebaker** [comment]
Perhaps you don´t even need to check for special processes? Or do you have a special use case for that. I think most of the time an Inputfield setup with your EditLinks schould have the links enabled. And the core has not much other processes that render Inputfields from pages I other than 'ProcessPageEdit', 'ProcessUser' I guess. The InputfieldPage module does also not check for processes before adding the internal "create new" link to the Inputfield as far as I know.

To stop the population of the EditLinks for Developers there could be a hookable function like InputfieldPage::___renderAddable. So if someone needs to stop the rendering of the EditLinks he could hook into that and stop it...
Just some thoughts...
