### ISSUE TITLE
Make "New" Links work with InputfieldChosenSelect

### ISSUE THREAD

**Issue by gingebaker** [thetuningspoon/AdminPageFieldEditLinks#9]
Hello

I needed the "Add New" behaviour for a Page field that uses [InputfieldChosenSelect]( https://github.com/LostKobrakai/InputfieldChosenSelect ).

This was not working because the "newPageCompleted" Event was not setup on the Select field since ChosenSelect uses another CSS Class Name.

The only thing I added to support that was one more Selector to the proper jquery find methods in AdminPageFieldEditLinks.js ([Line 40 and 49](https://github.com/thetuningspoon/AdminPageFieldEditLinks/blob/master/AdminPageFieldEditLinks.js)):

```js
$wrapper.find('div.InputfieldSelect.InputfieldPage-newPageLink,div.InputfieldChosenSelect.InputfieldPage-newPageLink').each(function() {
   //...
});

$wrapper.find('div.InputfieldSelectMultiple.InputfieldPage-newPageLink,div.InputfieldChosenSelectMultiple.InputfieldPage-newPageLink').each(function() {
   //...
});
```

So the new Selector Addons to Support ChosenSelect would be:
**,div.InputfieldChosenSelect.InputfieldPage-newPageLink**
and
**,div.InputfieldChosenSelect.InputfieldPage-newPageLink**

This seems to work fine!

Perhaps you can include this in feature versions?
Thank you

**Comment by thetuningspoon** [comment]
I've added this to the module but haven't tested, so let me know if there's any issue.
